const productsData = [
  {
    _id: 1,
    name: 'Airpods wireless Buetooth headphone',
    image: '/images/airpod.jpeg',
    description: 'long description of a product',
    brand: 'Apple',
    category: 'Electronic',
    price: 89.9,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
    isFeatured: true,
  },
  {
    _id: 2,
    name: 'Airpods wireless Buetooth headphone',
    image: '/images/applewatch.jpg',
    description: 'long description of a product',
    brand: 'Apple',
    category: 'Electronic',
    price: 89.9,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
    isFeatured: true,
  },
  {
    _id: 3,
    name: 'Airpods wireless Buetooth headphone',
    image: '/images/iphone13.jpg',
    description: 'long description of a product',
    brand: 'Apple',
    category: 'Electronic',
    price: 89.9,
    countInStock: 10,
    rating: 2.5,
    numReviews: 12,
    isFeatured: true,
  },
  {
    _id: 4,
    name: 'Airpods wireless Buetooth headphone',
    image: '/images/macbook air.jpg',
    description: 'long description of a product',
    brand: 'Apple',
    category: 'Electronic',
    price: 89.9,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
    isFeatured: true,
  },
];

export default productsData;
